### ISSUE TITLE
FYI: link to specification is broken/has changed

### ISSUE THREAD

**Issue by algonzalez** [jetpack-io/typeid#12]
Link to specification is broken. The spec appears to reside in the `README.md` file of the `/spec` folder.

Current: https://github.com/jetpack-io/typeid/blob/main/spec.md 
Working: https://github.com/jetpack-io/typeid/blob/main/spec/README.md

**Comment by loreto** [comment]
Thanks for catching, will fix ASAP

**Comment by loreto** [comment]
Fixed!
