### ISSUE TITLE
Mark C# (.NET) implementation validated against spec

### ISSUE THREAD

**Issue by TenCoKaciStromy** [jetpack-io/typeid#17]
Thanks for adding to the list!

I reimplemented the mentioned tests here ( https://github.com/TenCoKaciStromy/typeid-dotnet/blob/main/src/dotnet-typeid-tests/ValidationAgainstSpec_Tests.cs ).

**Comment by loreto** [comment]
Sorry for the delay. Go ahead and send me a PR marking your implementation as validated and I'll approve. Send it to our opensource monorepo, file: https://github.com/jetpack-io/opensource/blob/main/typeid/typeid/README.md

**Comment by loreto** [comment]
Addressed by https://github.com/jetpack-io/opensource/pull/77, closing
