### ISSUE TITLE
Add Swift Implementation

### ISSUE THREAD

**Issue by Frizlab** [jetpack-io/typeid#2]
Hi!

I’ve implemented a Swift lib for `typeid`: https://github.com/Frizlab/swift-typeid.
Can you add it in the implementations list?

Thanks!

**Comment by loreto** [comment]
@Frizlab  Thanks so much for contributing.

I've gone ahead and added your implementation to the list of implementations under:
https://github.com/jetpack-io/typeid#community-provided-implementations

You'll notice I have a "Validated Against Spec" column in the table. I recently added a bunch of tests for the
go implementation here: https://github.com/jetpack-io/typeid-go/blob/main/typeid_test.go

If you add the same tests and show that your implementation passes, I'll go ahead and mark it as validated.

**Comment by Frizlab** [comment]
Good! I searched for tests in the official implementation but did not find any; good to hear there are tests now 🙂

I'll add them in my lib and I'll come back to you.

**Comment by Frizlab** [comment]
It’s done in [version 0.2.0](https://github.com/Frizlab/swift-typeid/releases/tag/0.2.0). All the tests pass.
<img width="242" alt="Screenshot 2023-06-30 at 18 48 27" src="https://github.com/jetpack-io/typeid/assets/523041/f1a04f73-6fcd-4161-891e-6aa68564ae62">

**Comment by Frizlab** [comment]
And everything works on Linux too 🙂

**Comment by loreto** [comment]
Amazing! Send me a PR in our open source monorepo (https://github.com/jetpack-io/opensource/blob/main/typeid/typeid/README.md) adding `Yes, on 2023-06-30` to the validated column for your implementation.
