### ISSUE TITLE
Haskell implementation of typeid

### ISSUE THREAD

**Issue by MMZK1526** [jetpack-io/typeid#24]
I would be glad if you can kindly include this [Haskell implementation](https://github.com/MMZK1526/mmzk-typeid/) in the README.

There's no validation yet, but I will include them soon.

**Comment by loreto** [comment]
Hi @MMZK1526 , I'd be happy to. 

Could you send me a PR in our [opensource monorepo](https://github.com/jetpack-io/opensource) modifying the [README](https://github.com/jetpack-io/opensource/blob/main/typeid/typeid/README.md). Once we merge the code there, it'll be automatically published to this repo.

**Comment by loreto** [comment]
Closing since we just merged the change into the opensource monorepo
