### ISSUE TITLE
Add C# .NET implementation to the list

### ISSUE THREAD

**Issue by firenero** [jetpack-io/typeid#26]
Hi,

I've created a performance-oriented implementation of TypeId in C#: https://github.com/firenero/TypeId
What should be done to add it to the list and mark it as verified? I've seen the discussion about automated flow for validation (#23 ) but not sure if there is something in place already.

Also thanks for the reference implementation and examples of valid/invalid typeIds. They were really helpful during developing my library.

**Comment by loreto** [comment]
@firenero Thanks for contributing!

Send me:
1. A link to your tests and the github action showing them passing.
2. A PR adding your implementation for the README

I'll review and approve.

For the README PR, please send it in our opensource monorepo (https://github.com/jetpack-io/opensource/blob/main/typeid/typeid/README.md) and once it's checked in, it'll get published in the `typeid` repo automatically

**Comment by firenero** [comment]
Hi @loreto 

Tests are located in this folder: https://github.com/firenero/TypeId/tree/main/src/FastIDs.TypeId/TypeId.Tests/TypeIdTests
Successful build with tests: https://github.com/firenero/TypeId/actions/runs/5554606240/jobs/10144606542

**Comment by loreto** [comment]
Merged!

**Comment by firenero** [comment]
Thanks @loreto. Will you add the verification label yourself when you're done with the review or do I have to create a new PR for that?

**Comment by loreto** [comment]
Ah sorry, I missed that you hadn't added the verification date already. Go ahead and send me a PR and I'll approve!
