### ISSUE TITLE
Add Typescript Implementation

### ISSUE THREAD

**Issue by ongteckwu** [jetpack-io/typeid#3]
Implemented a typescript implementation. Needed for my work. Will post here soon after I polish it up. Thanks for this project!

**Comment by ongteckwu** [comment]
https://github.com/ongteckwu/typeid-ts heres the typescript implementation. Let me know if there are any issues.

**Comment by izakfilmalter** [comment]
Wow that was fast. I'm thinking about converting my app to this from UUID.

**Comment by loreto** [comment]
@ongteckwu  Thanks so much for contributing.

I've gone ahead and added your implementation to the list of implementations under:
https://github.com/jetpack-io/typeid#community-provided-implementations

You'll notice I have a "Validated Against Spec" column in the table. I recently added a bunch of tests for the
go implementation here: https://github.com/jetpack-io/typeid-go/blob/main/typeid_test.go

If you add the same tests and show that your implementation passes, I'll go ahead and mark it as validated.

Also, as a heads up, I too had a TypeScript implementation in the works (unfortunately we wrote them in parallel), which I also added to the list. If you are open to it, we can discuss how to merge the two implementations!

**Comment by ongteckwu** [comment]
@loreto very nice. Okay I will add the tests when I have the time. Thank you!

**Comment by ongteckwu** [comment]
@loreto I added the tests! =D

**Comment by loreto** [comment]
Amazing, send me a PR against this file https://github.com/jetpack-io/opensource/blob/main/typeid/typeid/README.md (in our `opensource` monorepo) marking your implementation as validated.

Add `Yes, on 2023-06-30` to the corresponding cell in the table.
