### ISSUE TITLE
Add Rust implementation

### ISSUE THREAD

**Issue by alisa101rs** [jetpack-io/typeid#4]
Implemented Rust version. Thanks for the project! 
Please add https://github.com/alisa101rs/typeid-rs to implementation list.

But also check https://github.com/jetpack-io/typeid-go/issues/2 issue.

**Comment by conradludgate** [comment]
Looks like you beat me to it. As an alternative impl, see mine https://docs.rs/type-safe-id/0.1.0/type_safe_id/

**Comment by loreto** [comment]
@alisa101rs and @conradludgate thank you both for contributing.

I've gone ahead and added both your implementations to the list of implementations under:
https://github.com/jetpack-io/typeid#community-provided-implementations

You'll noticed I have a "Validated Against Spec" column in the table. I recently added a bunch of tests for the
go implementation here: https://github.com/jetpack-io/typeid-go/blob/main/typeid_test.go

If you add the same tests and show that your implementation passes, I'll go ahead and mark it as validated.
