### ISSUE TITLE
Origin of base 32 alphabet

### ISSUE THREAD

**Issue by LLyaudet** [jetpack-io/typeid#5]
Hello,

This is more a comment than a true issue.
I was surprised to see [Crockford's alphabet](https://www.crockford.com/base32.html)
for something that looked familiar to me and was only from 2019.
Don't misunderstand me, I think this alphabet is convenient and maybe he was the first to propose exactly this choice of letters;
hence, he may deserve to be credited;
but for those interested in the topic, I suggest to look at:
https://ux.stackexchange.com/questions/53341/are-there-any-letters-numbers-that-should-be-avoided-in-an-id
from 2014
with link to:
https://github.com/tytso/pwgen/blame/master/pw_rand.c
from 2005
and if there had been GitHub since 1970, I would guess something earlier could be more easily found.
I think definitely <https://www.crockford.com/base32.html> should add bibliographic references.

Best regards,
    Laurent Lyaudet

**Comment by loreto** [comment]
@LLyaudet Thanks for pointing that out. I'm going to close this issue since there's nothing I have to change in the code, but the issue will remain browsable in this repo for folks that want to learn more about the origins of the base32 alphabet being used.

**Comment by LLyaudet** [comment]
I also spotted this today on HN : https://gajus.com/blog/avoiding-visually-ambiguous-characters-in-ids
