### ISSUE TITLE
Add .NET (C#) implementation

### ISSUE THREAD

**Issue by TenCoKaciStromy** [jetpack-io/typeid#6]
Hi!

I implemented a .NET lib: https://github.com/TenCoKaciStromy/typeid-dotnet

Could you add it in the implementations list?

Thanks!

**Comment by loreto** [comment]
@TenCoKaciStromy Thanks so much for contributing. 

I've gone ahead and added your implementation to the list of implementations under:
https://github.com/jetpack-io/typeid#community-provided-implementations

You'll noticed I have a "Validated Against Spec" column in the table. I recently added a bunch of tests for the
go implementation here: https://github.com/jetpack-io/typeid-go/blob/main/typeid_test.go

If you add the same tests and show that your implementation passes, I'll go ahead and mark it as validated.

**Comment by TenCoKaciStromy** [comment]
@loreto Thanks for adding to the list!

I reimplemented the mentioned tests here ( https://github.com/TenCoKaciStromy/typeid-dotnet/blob/main/src/dotnet-typeid-tests/ValidationAgainstSpec_Tests.cs ).
